// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/article": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以更新指定的文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章相关接口"
                ],
                "summary": "更新文章的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新文章的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateArticleFormsParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=200表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以创建文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章相关接口"
                ],
                "summary": "创建文章的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建文章的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.NewArticleFormsParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=200表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/article/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以查询文章详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章相关接口"
                ],
                "summary": "通过文章ID查询文章详细信息的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=200表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以删除指定的文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章相关接口"
                ],
                "summary": "删除单篇文章的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=200表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/articles": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以获得当前的所有文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章相关接口"
                ],
                "summary": "获取所有文章的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "p",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "size",
                        "name": "s",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "class",
                        "name": "c",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "tag",
                        "name": "t",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "n",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "status",
                        "name": "st",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "privilege",
                        "name": "pr",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以删除指定的文章 - 软删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章相关接口"
                ],
                "summary": "删除时,只会更新其状态为删除状态,不会删除数据库中的数据，恢复时将其恢复为指定状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除文章的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SoftDeleteArticleParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=200表示成功,其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "security": [
                    {
                        "No": []
                    }
                ],
                "description": "用于用户登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证相关接口"
                ],
                "summary": "用户登录接口",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/auth/password/modify": {
            "post": {
                "security": [
                    {
                        "No": []
                    }
                ],
                "description": "用于修改用户密码，不需要登录，需要验证旧密码，账户和验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证相关接口"
                ],
                "summary": "修改用户密码",
                "parameters": [
                    {
                        "description": "修改密码的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ModifyPasswordParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/auth/password/reset": {
            "post": {
                "security": [
                    {
                        "No": []
                    }
                ],
                "description": "用于用户重置密码，需要使用邮箱 - 功能未实现",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证相关接口"
                ],
                "summary": "重置密码接口",
                "parameters": [
                    {
                        "description": "重置密码的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResetPasswordParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "security": [
                    {
                        "No": []
                    }
                ],
                "description": "用户注册的接口，需要接收参数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证相关接口"
                ],
                "summary": "用户注册的接口",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/auth/verifycode": {
            "get": {
                "security": [
                    {
                        "No": []
                    }
                ],
                "description": "通过该接口可以获得基于数字的验证码，目前只支持数字验证码，后续可以更改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证相关接口"
                ],
                "summary": "获取数字验证码的接口",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseData"
                        }
                    }
                }
            }
        },
        "/class": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以更新类别",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类别相关接口"
                ],
                "summary": "更新类别(Class)的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新类别的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateClassParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseNoDataArea"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以创建类别",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类别相关接口"
                ],
                "summary": "创建类别(Class)的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建类别的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ClassCreateFormParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseCreateClass"
                        }
                    }
                }
            }
        },
        "/class/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以获得指定ID的类别",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类别相关接口"
                ],
                "summary": "根据类别ID查询类的信息（详细信息）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code字段为1000表示执行成功，其余表示出错",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseClassDetailList"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以删除类别",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类别相关接口"
                ],
                "summary": "删除类别(Class)的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseNoDataArea"
                        }
                    }
                }
            }
        },
        "/classes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以获得当前的所有文章",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类别相关接口"
                ],
                "summary": "获取所有类别（简略信息）的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseAllClassesList"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以删除多个类别",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "类别相关接口"
                ],
                "summary": "删除多个类别(Class)的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "待删除的class ID列表",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteMultiTagParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000成功，,返回data域中不为空代表对应的class删除失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseDeleteClass"
                        }
                    }
                }
            }
        },
        "/comment": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以创建评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论相关接口"
                ],
                "summary": "创建评论Comment的接口",
                "parameters": [
                    {
                        "description": "创建评论的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CommentCreateFormParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseNoDataArea"
                        }
                    }
                }
            }
        },
        "/comment/:id": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以删除单条评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论相关接口"
                ],
                "summary": "删除单条评论Comment的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "删除的评论的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseNoDataArea"
                        }
                    }
                }
            }
        },
        "/comments": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以分页获取评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论相关接口"
                ],
                "summary": "分页获取评论的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键字",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "评论类型 1-文章",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "对应的文章id",
                        "name": "atc_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "状态: 1-审核中 2-审核通过 3-审核未通过",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页号",
                        "name": "page_idx",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseNoDataArea"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以修改评论的状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论相关接口"
                ],
                "summary": "修改指定评论的状态的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除的评论的ID",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CommentDeleteFormParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseNoDataArea"
                        }
                    }
                }
            }
        },
        "/tag": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以更新Tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签相关接口"
                ],
                "summary": "更新标签(Tag)的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "更新标签的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateTagParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseNoDataArea"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以创建标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签相关接口"
                ],
                "summary": "创建标签(tag)的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建标签的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TagCreateFormParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseNoDataArea"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以删除多个Tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签相关接口"
                ],
                "summary": "删除多个标签(Tag)的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "删除多个标签的参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteMultiTagParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseNoDataArea"
                        }
                    }
                }
            }
        },
        "/tag/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以获得当前标签的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签相关接口"
                ],
                "summary": "根据ID获取标签的详细信息的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseTagDetailList"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以删除单个Tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签相关接口"
                ],
                "summary": "删除单个标签(Tag)的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code=1000表示成功其余失败",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseNoDataArea"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过该接口可以获得当前的所有标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签相关接口"
                ],
                "summary": "获取所有标签（简略信息）的接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token(jwt)",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller._ResponseAllTagList"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ResponseCodeType": {
            "type": "integer",
            "enum": [
                1000,
                1001,
                1002,
                1003,
                1004,
                1005,
                1006,
                1007,
                1008,
                1009,
                1010,
                1011,
                1012,
                1013,
                1014,
                1015,
                1016,
                1017,
                1018
            ],
            "x-enum-varnames": [
                "CodeSuccess",
                "CodeParameterInvalid",
                "CodeUserNotExist",
                "CodeUserExist",
                "CodePasswordError",
                "CodeServerBusy",
                "CodeTokenInvaild",
                "CodeTokenEmpty",
                "CodeNeedReLogin",
                "CodeCommunityIdInvalid",
                "CodeVerifyCodeInvaild",
                "CodeArticleTitleExisted",
                "CodeArticleNotExisted",
                "CodeHaveArticleInClass",
                "CodeTagExisted",
                "CodeTagNotExisted",
                "CodeClassNotExisted",
                "CodeClassNameExisted",
                "CodeCreateCommentFailed"
            ]
        },
        "controller.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/controller.ResponseCodeType"
                },
                "data": {
                    "description": "omitempty 该字段为空时忽略"
                },
                "msg": {}
            }
        },
        "controller._ResponseAllClassesList": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/controller.ResponseCodeType"
                },
                "data": {
                    "description": "` + "`" + `json:\"data,omitempty\"` + "`" + ` //omitempty 该字段为空时忽略",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ResponseClassBrief"
                    }
                },
                "msg": {}
            }
        },
        "controller._ResponseAllTagList": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/controller.ResponseCodeType"
                },
                "data": {
                    "description": "` + "`" + `json:\"data,omitempty\"` + "`" + ` //omitempty 该字段为空时忽略",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ResponseTagBrief"
                    }
                },
                "msg": {}
            }
        },
        "controller._ResponseClassDetailList": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/controller.ResponseCodeType"
                },
                "data": {
                    "description": "` + "`" + `json:\"data,omitempty\"` + "`" + ` //omitempty 该字段为空时忽略",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ResponseClassDetail"
                        }
                    ]
                },
                "msg": {}
            }
        },
        "controller._ResponseCreateClass": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/controller.ResponseCodeType"
                },
                "data": {
                    "description": "` + "`" + `json:\"data,omitempty\"` + "`" + ` //omitempty 该字段为空时忽略",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ResponseClassBrief"
                        }
                    ]
                },
                "msg": {}
            }
        },
        "controller._ResponseDeleteClass": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/controller.ResponseCodeType"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "msg": {}
            }
        },
        "controller._ResponseNoDataArea": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/controller.ResponseCodeType"
                },
                "msg": {}
            }
        },
        "controller._ResponseTagDetailList": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/controller.ResponseCodeType"
                },
                "data": {
                    "description": "` + "`" + `json:\"data,omitempty\"` + "`" + ` //omitempty 该字段为空时忽略",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ResponseTagDetail"
                        }
                    ]
                },
                "msg": {}
            }
        },
        "models.ClassCreateFormParams": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.CommentCreateFormParams": {
            "type": "object",
            "properties": {
                "article_id": {
                    "description": "被评论的文章ID",
                    "type": "string",
                    "example": "0"
                },
                "content": {
                    "description": "评论内容",
                    "type": "string"
                },
                "email": {
                    "description": "评论人的邮箱 - 不强制要求",
                    "type": "string"
                },
                "parent_comment_id": {
                    "description": "RootCommentId   uint   ` + "`" + `json:\"root_comment_id,string\"` + "`" + `   // 根评论的ID",
                    "type": "string",
                    "example": "0"
                },
                "status": {
                    "description": "评论状态：0-审核中 1-审核通过 2-审核未通过",
                    "type": "integer"
                },
                "type": {
                    "description": "评论种类 1- 表示文章评论",
                    "type": "integer"
                },
                "user_name": {
                    "description": "评论人名字 - 强制要求",
                    "type": "string"
                }
            }
        },
        "models.CommentDeleteFormParams": {
            "type": "object",
            "properties": {
                "ids": {
                    "description": "id列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.DeleteMultiArticleParams": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "description": "待删除的文章ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.DeleteMultiTagParams": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "description": "待删除的TagID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.LoginParams": {
            "type": "object",
            "required": [
                "password",
                "username",
                "verify_code"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "verify_code": {
                    "description": "验证码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.VerifyCodeParams"
                        }
                    ]
                }
            }
        },
        "models.ModifyPasswordParams": {
            "type": "object",
            "required": [
                "new_password",
                "old_password",
                "username",
                "verify_code"
            ],
            "properties": {
                "new_password": {
                    "description": "新密码",
                    "type": "string"
                },
                "old_password": {
                    "description": "旧密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                },
                "verify_code": {
                    "description": "验证码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.VerifyCodeParams"
                        }
                    ]
                }
            }
        },
        "models.NewArticleFormsParams": {
            "type": "object",
            "required": [
                "class_id",
                "content",
                "title"
            ],
            "properties": {
                "class_id": {
                    "description": "文章所属的分类 - 比如教程，分享等",
                    "type": "string",
                    "example": "0"
                },
                "content": {
                    "description": "文章内容",
                    "type": "string"
                },
                "en_comment": {
                    "description": "是否允许评论 false-不允许 true-允许",
                    "type": "boolean"
                },
                "image": {
                    "description": "文章缩略图",
                    "type": "string"
                },
                "privilege": {
                    "description": "文章权限 0-公开 1-私有",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PrivilegeType"
                        }
                    ]
                },
                "status": {
                    "description": "文章状态 0-草稿 1-发布 2-删除",
                    "type": "integer"
                },
                "summary": {
                    "description": "文章的摘要信息",
                    "type": "string"
                },
                "tag_id_list": {
                    "description": "文章标签-标签可以为空",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TagFormsParams"
                    }
                },
                "title": {
                    "description": "文章标题",
                    "type": "string"
                },
                "top_flag": {
                    "description": "是否置顶标志 false-没有置顶 true-置顶",
                    "type": "boolean"
                }
            }
        },
        "models.PrivilegeType": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-comments": {
                "PrivilegePrivte": "2- 当前文章私有，客户端不可见",
                "PrivilegePublic": "1 - 当前文章是公开的，客户端可见（默认）"
            },
            "x-enum-varnames": [
                "PrivilegePublic",
                "PrivilegePrivte"
            ]
        },
        "models.ResetPasswordParams": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "models.ResponseClassBrief": {
            "type": "object",
            "properties": {
                "atc_count": {
                    "description": "该分类下包含的文章数量",
                    "type": "integer"
                },
                "class_id": {
                    "description": "类别ID - 由应用层生成",
                    "type": "string",
                    "example": "0"
                },
                "name": {
                    "description": "类别名称",
                    "type": "string"
                }
            }
        },
        "models.ResponseClassDetail": {
            "type": "object",
            "properties": {
                "atc_count": {
                    "description": "该分类下包含的文章数量",
                    "type": "integer"
                },
                "class_id": {
                    "description": "类别ID - 由应用层生成",
                    "type": "string",
                    "example": "0"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "desc": {
                    "description": "类别的描述信息",
                    "type": "string"
                },
                "name": {
                    "description": "类别名称",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "models.ResponseTagBrief": {
            "type": "object",
            "properties": {
                "atc_count": {
                    "description": "该标签下包含的文章数量",
                    "type": "integer"
                },
                "name": {
                    "description": "类别名称",
                    "type": "string"
                },
                "tag_id": {
                    "description": "标签ID - 由应用层生成",
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "models.ResponseTagDetail": {
            "type": "object",
            "properties": {
                "atc_count": {
                    "description": "该标签下包含的文章数量",
                    "type": "integer"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "desc": {
                    "description": "标签的描述信息",
                    "type": "string"
                },
                "name": {
                    "description": "类别名称",
                    "type": "string"
                },
                "tag_id": {
                    "description": "标签ID - 由应用层生成",
                    "type": "string",
                    "example": "0"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "models.SignUpParams": {
            "type": "object",
            "required": [
                "password",
                "re_password",
                "username",
                "verify_code"
            ],
            "properties": {
                "email": {
                    "description": "邮箱 - 仅在重置密码时，接收验证码使用",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "re_password": {
                    "description": "确认密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名 - 用户名作为唯一标识，不允许重复",
                    "type": "string"
                },
                "verify_code": {
                    "description": "验证码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.VerifyCodeParams"
                        }
                    ]
                }
            }
        },
        "models.SoftDeleteArticleParams": {
            "type": "object",
            "required": [
                "del_flag",
                "ids"
            ],
            "properties": {
                "del_flag": {
                    "description": "true - 删除  false - 恢复",
                    "type": "boolean"
                },
                "ids": {
                    "description": "待删除的文章ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.TagCreateFormParams": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.TagFormsParams": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "tag id",
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "models.UpdateArticleFormsParams": {
            "type": "object",
            "required": [
                "article_id",
                "class_id",
                "content",
                "title"
            ],
            "properties": {
                "article_id": {
                    "type": "string",
                    "example": "0"
                },
                "class_id": {
                    "description": "文章所属的分类 - 比如教程，分享等",
                    "type": "string",
                    "example": "0"
                },
                "content": {
                    "description": "文章内容",
                    "type": "string"
                },
                "en_comment": {
                    "description": "是否允许评论 false-不允许 true-允许",
                    "type": "boolean"
                },
                "image": {
                    "description": "文章缩略图",
                    "type": "string"
                },
                "privilege": {
                    "description": "文章权限 0-公开 1-私有",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PrivilegeType"
                        }
                    ]
                },
                "status": {
                    "description": "文章状态 0-草稿 1-发布 2-删除",
                    "type": "integer"
                },
                "summary": {
                    "description": "文章的摘要信息",
                    "type": "string"
                },
                "tag_id_list": {
                    "description": "文章标签-标签可以为空",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TagFormsParams"
                    }
                },
                "title": {
                    "description": "文章标题",
                    "type": "string"
                },
                "top_flag": {
                    "description": "是否置顶标志 false-没有置顶 true-置顶",
                    "type": "boolean"
                }
            }
        },
        "models.UpdateClassParams": {
            "type": "object",
            "required": [
                "class_id",
                "name"
            ],
            "properties": {
                "class_id": {
                    "type": "string",
                    "example": "0"
                },
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.UpdateTagParams": {
            "type": "object",
            "required": [
                "name",
                "tag_id"
            ],
            "properties": {
                "desc": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tag_id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "models.VerifyCodeParams": {
            "type": "object",
            "required": [
                "code",
                "id"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "NgBlog",
	Description:      "NgBlog Go博客项目 API 接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
